# Generated by Django 4.2.20 on 2025-04-04 21:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Auctions",
            new_name="Auction",
        ),
    ]
