# Generated by Django 4.2.20 on 2025-04-10 21:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0004_auction_auctioneer_alter_auction_price_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bid",
            name="bidder",
        ),
    ]
